services:
  springboot-app:
    image: tech:latest
    build: .
    ports:
      - "2002:2002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tech-mysql-db:3306/CyfrifProTech
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - tech-mysql-db
    networks:
      - tech-network

  tech-mysql-db:
    image: mysql:8
    container_name: tech-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CyfrifProTech
    ports:
      - "3302:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tech-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "83:80"
      - "1443:443"
    volumes:
      - ./nginx/cyfrifprotech.com.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount certificatesss
    depends_on:
      - springboot-app
    networks:
      - tech-network

volumes:
  mysql_data:

networks:
  tech-network:
