version: '3.8'

networks:
  tech-network:
    driver: bridge

services:
  springboot-app:
    image: tech:latest
    build: .
    ports:
      - "2002:2002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tech-mysql-db:3306/CyfrifProTech
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      tech-mysql-db:
        condition: service_healthy
    networks:
      - tech-network

  tech-mysql-db:
    image: mysql:8
    container_name: tech-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CyfrifProTech
    ports:
      - "3302:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tech-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  nginx:
    image: nginx:latest
    container_name: tech-nginx
    restart: always
    ports:
      - "83:83"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt  # Mount SSL certificates
      - ./html:/usr/share/nginx/html
    depends_on:
      - springboot-app
    networks:
      - tech-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/html --quiet; sleep 12h & wait $${!}; done'"
    networks:
      - tech-network

volumes:
  mysql_data:
